# Generated by Django 3.1.2 on 2020-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosocial', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
