# Generated by Django 3.1.2 on 2020-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nosocial',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
