# Generated by Django 3.1.2 on 2020-10-09 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlAsistencia', '0002_auto_20201008_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleados',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistencia del dia'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellidos',
            field=models.CharField(max_length=40, verbose_name='Apellidos del empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cargo',
            field=models.CharField(max_length=30, verbose_name='Cargo que desempeña'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombres del empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nosocial',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Numero social'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono de contacto'),
        ),
        migrations.CreateModel(
            name='asistencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de asistencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlAsistencia.empleados')),
            ],
            options={
                'verbose_name': 'Asitencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
